"""Generate evaluation/REPORT.md from saved artefacts only (no hand-entered numbers).

Usage: python -m src.report
"""
from __future__ import annotations

import json
import sys

import pandas as pd

from src.config import INTENTS, load_config, path, resolve
from src.policy.emergency import red_flags


def _load(p):
    return json.loads(p.read_text()) if p.exists() else None


def fmt(x, nd=4):
    return "n/a" if x is None else (f"{x:.{nd}f}" if isinstance(x, float) else str(x))


def main() -> int:
    cfg = load_config()
    ev = path(cfg, "evaluation_dir")
    log = _load(path(cfg, "changelog"))
    split = _load(path(cfg, "train").parent / "split_summary.json")
    comp = _load(ev / "baseline_results.json")
    templates = _load(path(cfg, "response_templates"))
    emo_dir = path(cfg, "emotion_model_dir")
    emo_cfg = _load(emo_dir / "config.json")
    L = ["# Implementation report", "",
         "_Generated by `python -m src.report` from files in `data/processed/`, `models/` and `evaluation/`._", ""]

    L += ["## Dataset", "",
          f"- Original (seed) dataset size: **{log['original_size']}** rows (20 per intent)",
          f"- Expansion candidates: {log['expansion_candidates']}",
          f"- Enhanced dataset size: **{log['enhanced_size']}** rows", ""]
    for s in log["steps"]:
        L.append(f"- {s['step'].replace('_', ' ')}: {s['count']}")
    L += ["", "| intent | original kept | added | total |", "|---|---|---|---|"]
    for k in INTENTS:
        src = log["per_intent_by_source"][k]
        L.append(f"| {k} | {src.get('original', 0)} | {src.get('expansion', 0)} | {log['enhanced_per_intent'][k]} |")
    L += ["", f"Split (seed {split['seed']}): train **{split['sizes']['train']}**, validation "
          f"**{split['sizes']['validation']}**, test **{split['sizes']['test']}**; out-of-domain "
          f"validation {split['ood_sizes']['validation']}, out-of-domain test {split['ood_sizes']['test']}.", "",
          f"Leakage check: exact overlap train/test = {split['leakage']['test']['n_exact_overlap']}; max same-intent "
          f"char-n-gram similarity of a test item to any train item = "
          f"{split['leakage']['test']['max_similarity_to_train_same_intent']:.3f} "
          f"(grouping threshold {split['leakage_group_threshold']}).", ""]

    n_emos = len(next(iter(templates.values())))
    L += ["## Emotions and templates", "",
          f"- Emotion labels in templates: **{n_emos}**; templates: **{sum(len(v) for v in templates.values())}** "
          f"({len(templates)} intents x {n_emos})."]
    if emo_cfg:
        labels = [emo_cfg["id2label"][str(i)] for i in range(len(emo_cfg["id2label"]))]
        L.append(f"- Verified against `{cfg['emotion_model']['model_name']}` config.id2label: "
                 f"{len(labels)} labels, problem_type={emo_cfg.get('problem_type')}, "
                 f"match={sorted(labels) == sorted(templates['greeting'])}.")
    else:
        L.append(f"- `{cfg['emotion_model']['model_name']}` not downloaded in this environment; the label set "
                 "is the canonical GoEmotions inventory and is verified against the model's id2label at load time "
                 "(`EmotionClassifier` raises on mismatch).")
    L.append("")

    L += ["## Intent models (held-out test set)", ""]
    if not comp:
        L += ["No evaluation results yet - run `python -m src.intent.evaluate`.", ""]
    else:
        models = comp["models"]
        L += ["| model | val macro-F1 | test accuracy | macro P | macro R | macro F1 | weighted F1 | latency (ms, 1 query) | size (MB) |",
              "|---|---|---|---|---|---|---|---|---|"]
        for k, r in models.items():
            t = r["test"]
            L.append(f"| {k} | {r['validation']['macro_f1']:.4f} | {t['accuracy']:.4f} | {t['macro_precision']:.4f} | "
                     f"{t['macro_recall']:.4f} | {t['macro_f1']:.4f} | {t['weighted_f1']:.4f} | "
                     f"{r['latency_single_query']['mean_ms']} | {r['model_size_mb']} |")
        for k in ("tfidf_logreg", "bert"):
            if k not in models:
                L.append(f"| {k} | not run | | | | | | | |")
        sel = comp["selection"]
        L += ["", f"**Selected model: `{sel['selected']}`** - rule: {sel['rule']} (decided on validation, before test)."]
        if "bert" not in models:
            L.append("BERT was not trained in this environment (Hugging Face download blocked), so this selection "
                     "is among available candidates only and must be re-run after BERT training.")
        L.append("")
        for k, r in models.items():
            s, e, c = r["selective_prediction_test"], r["emergency_routing_test"], r["calibration_test"]
            L += [f"### {k}", "",
                  "Most confused pairs (test, both directions): " + ", ".join(
                      f"{p['pair'][0]} <-> {p['pair'][1]} ({p['count']})" for p in r["most_confused_pairs_symmetric"][:6]),
                  "", "Lowest-recall intents: " + ", ".join(f"{x['intent']} ({x['recall']:.2f})" for x in r["lowest_recall_intents"]),
                  "", f"- Calibration: T = {c['temperature']:.3f}; test ECE {c['ece_uncalibrated']:.4f} (T=1) -> "
                  f"{c['ece_calibrated']:.4f} (scaled)",
                  f"- Confidence threshold {s['threshold']:.2f}: in-domain coverage {s['in_domain_coverage']:.3f}, "
                  f"selective accuracy {fmt(s['selective_accuracy'])}, confident errors {s['confident_errors']}/"
                  f"{s['errors_total']} errors; OOD false-accept rate {s['ood_false_accept_rate']:.3f} "
                  f"({len(s['ood_false_accepts'])}/{s['ood_test_size']})",
                  f"- Emergency threshold {e['threshold']:.2f} on P(emergency): recall {e['recall_on_test']:.3f} on test "
                  f"emergencies (arg-max recall {e['argmax_recall_on_test']:.3f}); false-emergency rate "
                  f"{e['false_emergency_rate_in_domain']:.3f} in-domain, {e['false_emergency_rate_ood']:.3f} OOD", ""]
                  
    df = pd.read_csv(path(cfg, "test"), keep_default_na=False)
    rf = df["text"].map(lambda t: bool(red_flags(t)))
    em = df["intent"] == "emergency_assistance"
    L += ["## Red-flag safety net (test split)", "",
          f"- Recall on emergency test queries: {rf[em].mean():.3f} ({int(rf[em].sum())}/{int(em.sum())}); "
          f"non-emergency test queries flagged: {int(rf[~em].sum())}/{int((~em).sum())}.",
          "- Note: patterns were written while authoring the whole dataset, so this is not a fully blind estimate.", ""]
    if comp:
        from src.intent.predictor import load_intent_classifier
        clf = load_intent_classifier(comp["selection"]["selected"], cfg)
        p_em = clf.predict_proba(df["text"].tolist())[:, clf.labels.index("emergency_assistance")]
        routed = (p_em >= clf.emergency_threshold) | rf.to_numpy()
        missed = df["text"][em & ~routed].tolist()
        L += [f"- Combined emergency routing ({comp['selection']['selected']} P(emergency) >= "
              f"{clf.emergency_threshold:.2f} OR red flag): recall {routed[em].mean():.3f} "
              f"({int(routed[em].sum())}/{int(em.sum())}); non-emergency test queries routed to emergency: "
              f"{int(routed[~em].sum())}/{int((~em).sum())}.",
              "- Missed emergencies: " + ("; ".join(f'"{t}"' for t in missed) if missed else "none"), ""]
    (ev / "REPORT.md").write_text("\n".join(L))
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
