"""
Symbolic Pattern Completion (SPC) task — LPP paper item #11.

Paper: Results §"LPP-informed tasks for model evaluation" (page 6); Supplement
§1.1.2 (page 18) and Algorithm 2; Table 2 example (page 9). Evaluation:
Materials & Methods §"Evaluating LLMs" (page 13): "For SPC we compute
character-level F1 and average across samples. [...] 10 in-context examples.
max_new_tokens=8."

Each item is a length-SEQ_LEN symbolic sequence generated by a hidden rule. The
model sees the first (SEQ_LEN - MASK_LEN) symbols and must produce the final
MASK_LEN symbols. Grading is character-level F1 over the multiset of predicted
vs. gold characters.
"""
from __future__ import annotations

import random
from collections import Counter

ALPHABET = ["A", "B", "C", "D", "E", "F"]
SEQ_LEN = 12         # paper: sequences of length 12
MASK_LEN = 3         # paper: last 3 symbols are masked

RULES = ("alternation", "mirror", "progression", "modular_increment", "nested")


# ---------------------------------------------------------------------------
# Rule generators. Each returns a full length-SEQ_LEN list of symbols so the
# gold continuation (last MASK_LEN symbols) is well defined. Paper Alg. 2 /
# Supplement §1.1.2.
# ---------------------------------------------------------------------------
def _gen_alternation(rng: random.Random) -> list[str]:
    a, b = rng.sample(ALPHABET, 2)
    return [a if i % 2 == 0 else b for i in range(SEQ_LEN)]


def _gen_mirror(rng: random.Random) -> list[str]:
    # Palindrome: first half random, second half mirrors it.
    half = (SEQ_LEN + 1) // 2
    left = [rng.choice(ALPHABET) for _ in range(half)]
    seq = left + left[::-1]
    return seq[:SEQ_LEN]


def _gen_progression(rng: random.Random) -> list[str]:
    # A fixed cycle of k symbols repeated to fill the sequence.
    k = rng.randint(2, 4)
    cycle = rng.sample(ALPHABET, k)
    return [cycle[i % k] for i in range(SEQ_LEN)]


def _gen_modular_increment(rng: random.Random) -> list[str]:
    # Arithmetic progression over alphabet indices, mod len(ALPHABET).
    start = rng.randrange(len(ALPHABET))
    step = rng.randint(1, len(ALPHABET) - 1)
    return [ALPHABET[(start + i * step) % len(ALPHABET)] for i in range(SEQ_LEN)]


def _gen_nested(rng: random.Random) -> list[str]:
    # Composition of two rules (paper §1.1.2 "nested"): a two-symbol
    # alternation whose symbol pair advances (progression) every block.
    a, b = rng.sample(ALPHABET, 2)
    block = rng.randint(2, 3)
    seq = []
    shift = 0
    for i in range(SEQ_LEN):
        if i > 0 and i % (2 * block) == 0:
            shift += 1
        base = a if (i // block) % 2 == 0 else b
        idx = (ALPHABET.index(base) + shift) % len(ALPHABET)
        seq.append(ALPHABET[idx])
    return seq


_GENERATORS = {
    "alternation": _gen_alternation,
    "mirror": _gen_mirror,
    "progression": _gen_progression,
    "modular_increment": _gen_modular_increment,
    "nested": _gen_nested,
}


def generate_spc(n: int = 100, seed: int = 42) -> list[dict]:
    """
    Return n items: {'prompt_prefix': str, 'gold': str, 'rule': str}.

    'prompt_prefix' is the first SEQ_LEN - MASK_LEN symbols (no spaces); 'gold'
    is the final MASK_LEN symbols. Rules are cycled so all five appear roughly
    equally. Deterministic in `seed`.
    """
    rng = random.Random(seed)
    items = []
    for i in range(n):
        rule = RULES[i % len(RULES)]
        seq = _GENERATORS[rule](rng)
        prefix = "".join(seq[:SEQ_LEN - MASK_LEN])
        gold = "".join(seq[SEQ_LEN - MASK_LEN:])
        items.append({"prompt_prefix": prefix, "gold": gold, "rule": rule})
    return items


def prompt_template(sequence_prefix: str,
                    in_context_examples: list[tuple[str, str]]) -> str:
    """
    Build the SPC prompt (Table 2 format) with `in_context_examples` (paper: 10)
    prepended as full Sequence/Answer pairs.
    """
    header = (
        "You are given a symbolic sequence. Continue it by writing exactly the "
        f"next {MASK_LEN} symbols, without spaces or explanations.\n"
    )
    shots = "".join(
        f"Sequence: {pfx}\nAnswer: {ans}\n\n" for pfx, ans in in_context_examples
    )
    return f"{header}\n{shots}Sequence: {sequence_prefix}\nAnswer:"


def char_f1(pred: str, gold: str) -> float:
    """
    Character-level F1 over the multiset of characters (paper §Evaluating LLMs).
    Returns 0.0 when either side is empty.
    """
    if not pred or not gold:
        return 0.0
    pc, gc = Counter(pred), Counter(gold)
    overlap = sum((pc & gc).values())
    if overlap == 0:
        return 0.0
    precision = overlap / sum(pc.values())
    recall = overlap / sum(gc.values())
    return 2 * precision * recall / (precision + recall)


def parse_prediction(raw: str) -> str:
    """
    Extract the model's predicted symbols. The prompt ends with "Answer:" and
    forbids spaces/explanations, so a well-behaved output is the bare symbols.
    We drop surrounding whitespace, skip leading punctuation, then take the
    leading run of alphabet symbols (up to MASK_LEN). Reading the *leading* run
    rather than every A-F character avoids scavenging symbols out of stray
    English words the model might append.
    """
    s = "".join(raw.split()).upper()
    i = 0
    while i < len(s) and not s[i].isalpha():   # skip leading quotes/colons/etc.
        i += 1
    out = []
    for c in s[i:]:
        if c in ALPHABET:
            out.append(c)
            if len(out) == MASK_LEN:
                break
        else:
            break
    return "".join(out)


def grade_spc(records: list[dict]) -> dict:
    if not records:
        return {"n": 0, "mean_char_f1": 0.0}
    return {
        "n": len(records),
        "mean_char_f1": sum(r["char_f1"] for r in records) / len(records),
    }
